apiVersion: v1
kind: Service
metadata:
  name: intelligence
  namespace: platform
  labels:
    app: intelligence
    component: ml-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: intelligence
